### ISSUE TITLE
Tutorials here does not work: https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-connect-wordpress-to-mysql-managed-database

### ISSUE THREAD

**Issue by yingdi11** [awsdocs/amazon-lightsail-developer-guide#18] opened 2020-03-14 22:53 UTC
https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-connect-wordpress-to-mysql-managed-database

mysqldump -u root --databases bitnami_wordpress --single-transaction --compress --order-by-primary -p$(cat /home/bitnami/bitnami_application_password) | mysql -u DbUserName --host DbEndpoint --password

will result in below errors 

ERROR 1045 (28000): Access denied for user 'dbmasteruser'@'172.26.3.110' (using password: 
NO)

**Comment by rlatino** [comment] 2020-03-24 16:09
Closing as a duplicate of https://github.com/awsdocs/amazon-lightsail-developer-guide/issues/17

Refer to the other issue for more information.

**Closed by rlatino** 2020-03-24 16:09 UTC
